server:
  port: 8080
  servlet:
    context-path: /agendador

spring:
  profiles:
    active: local
  application:
    name: servicos

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sch_agendador
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true